version: '3.3'
services:
    audible_sync:
        container_name: audible_sync
        volumes:
            - './data:/data'
        environment:
          - Audible__Locale=germany
          - Audible__Credentials__UserName=${AUDIBLE_USERNAME}
          - Audible__Credentials__Password=${AUDIBLE_PASSWORD}
        # image: ghcr.io/jkamsker/audiblesyncservice/audible_sync_service:latest # Run with latest version
        build: 
            context: ./
            dockerfile: Dockerfile