version: '3.3'
services:
    audible-sync:
        container_name: audible-sync
        volumes:
            # - './data/tmp:/data/tmp'
            # - './data/out:/data/out'
            # - './data/settings:/data/settings'
            - './data:/data'
        # image: a-sync
        environment:
          - Audible__Credentials__UserName=${AUDIBLE_USERNAME}
          - Audible__Credentials__Password=${AUDIBLE_PASSWORD}
          - Audible__Headless=false
        build: 
            context: ./
            dockerfile: Dockerfile