name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  IMAGE_NAME: AudibleSyncService

# $PWD seems to be the rootDirectory of the repo
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      - 
        name: Output Run Number
        run: echo ${{github.run_number}}
      - 
        name: Calculate Publishing Variables
        run: |
          IMAGE_ID=${{ github.repository }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=0.1.${{github.run_number}}

          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"
      - 
        name: Echoing the publishing Variables
        run: |
          echo IMAGE_ID="${{env.IMAGE_ID}}"
          echo VERSION="${{env.VERSION}}"
      - 
        name: Init Project
        run: |
          chmod +x ./git-init.sh
          ./git-init.sh
      - 
        name: Build project
        run: docker build -t audible_sync_service .
      - 
        name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - 
        name: Push image to Github Registry
        run: |
          # Push to github registry
          CURRENT_ID=docker.pkg.github.com/$IMAGE_ID/audible_sync_service
          docker tag audible_sync_service $CURRENT_ID:$VERSION
          docker tag audible_sync_service $CURRENT_ID:latest

          docker push $CURRENT_ID:$VERSION
          docker push $CURRENT_ID:latest
      - 
        name: Log into GitHub registry
        run: echo "${{ secrets.DOCKER_HUB_SECRET }}" | docker login -u jkamsker --password-stdin
      - 
        name: Push image to Docker Registry
        run: |
          # Push to github registry
          CURRENT_ID=jkamsker/audible_sync_service
          docker tag audible_sync_service $CURRENT_ID:$VERSION
          docker tag audible_sync_service $CURRENT_ID:latest

          docker push $CURRENT_ID:$VERSION
          docker push $CURRENT_ID:latest